---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "pytest"
        env: DB_PORT=${{ secrets.DB_PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          CHATGPT_API_KEY=${{ secrets.CHATGPT_API_KEY }}
          ENV=${{ secrets.ENV }}
          VERSION=${{ secrets.VERSION }}
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
